# torchlego 

**This is an early preview**

High quality Neural Networks built with reausable blocks in PyTorch

![alt](https://raw.githubusercontent.com/FrancescoSaverioZuppichini/torchlego/develop/doc/images/lego.jpg)

*Photo by Ryan Quintal on Unsplash*

## Motivation

This library aims to create new components to make developing and writing neural networks faster and easier.

## Installation

### pip
You can install using pip

```bash
pip install git+https://github.com/FrancescoSaverioZuppichini/torchlego
```

## Quick Tour

In [1]:
%load_ext autoreload
%autoreload 2

## Building blocks

It follows a list of useful small components made to increase your code readibily and development. Just like lego, when combined, they can become anything!

#### Convs
Most of the times you will use $3x3$ conv or $1x1$ convs followed by *batchnorm* and an *activation function*

In [2]:
from torchlego import conv3x3

conv3x3(32, 64)

Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/conv3x3.png?raw=true)

In [3]:
from torchlego import conv3x3_bn

conv3x3_bn(32, 64)

Sequential(
  (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/conv3x3_bn.png?raw=true)

In [4]:
from torchlego import conv3x3_bn_act

conv3x3_bn_act(32, 64)

Sequential(
  (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
)

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/conv3x3_bn_act.png?raw=true)

Optionally, you can always pass your own activation function

In [5]:
from torch.nn import SELU
conv3x3_bn_act(32, 64, act=SELU)

Sequential(
  (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1))
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): SELU()
)

Also, we have `conv1x1`

In [6]:
from torchlego.blocks import conv1x1

conv1x1(32, 64)

Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1))

### InputForward

Many times we need to pass an input to multiple modules and do something with the results. This is went `InputForward` comes in handy! `aggr_func` takes as input a list where each entry is the output from one of the modules

In [7]:
import torch
from torchlego.blocks import InputForward, Lambda

blocks = [Lambda(lambda x: x), Lambda(lambda x: x)]
InputForward(blocks, aggr_func=lambda x: torch.tensor(x).sum())(torch.tensor([1]))

tensor(2)

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/InputForward.png?raw=true)

#### Cat

An `InputForward` instance that concates the outputs

In [8]:
import torch
from torchlego.blocks import Cat, Lambda


blocks = [Lambda(lambda x: x), Lambda(lambda x: x)]

Cat(blocks)(torch.tensor([1]))

tensor([1, 1])

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Cat.png?raw=true)

## Residual Connection

Redisual connection are a big thing. They probably are most know from *resnet* paper (even if Schmidhuber did something very similar a long time ago). You can use `torchlego` to easily create **any** residual connection that you may need.

### Residual

The main building block is the `Residual` class. Basically, it applys a function on the input and the output of a `blocks`.

In [9]:
import torch
from torchlego.blocks import Residual, Lambda

x = torch.tensor([1])
block = Lambda(lambda x: x)


res = Residual(block, res_func=lambda x, res: x + res)
res(x)

tensor([2])

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Residual.png?raw=true)

#### shortcut
We can also apply a function on the residual, this operation is called `shortcut`.

In [10]:
res = Residual(block, res_func=lambda x, res: x + res, shortcut=lambda x: x * 2)
res(x)

tensor([3])

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Residual_shorcut.png?raw=true)

You can also not pass the `.res_func`, in that case the residual will be passed as second parameter to the `blocks`.

#### Multiple lever residuals

If you pass an array of `nn.ModuleList`, we assume you want to pass residual trought each respective layer. In the following example all the `A` layer just compute input + 1 the input while the `B` layers add the residual with the current input. Notice that the `B.forward` function takes as second argument the residual.

In [11]:
import torch.nn as nn

class A(nn.Module):
    def forward(self, x):
        return x + 1
    
class B(nn.Module):
    def forward(self, x, res):
        return x + res
        
down = nn.ModuleList([A(), A()])
up = nn.ModuleList([B(), B()])
res = Residual([down, up])
res(x)

tensor([8])

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Residual_blocks.png?raw=true)

Be awere that only the first `n` residuals will be passed, where `n` is the len of the second blocks. I know, it sound confusing, but let's see an example.

In [12]:
import torch.nn as nn


class B(nn.Module):
    def forward(self, x, res = None):
        x = x if res is None else x + res
        return x 
        
down = nn.ModuleList([A(), A()])
up = nn.ModuleList([B()])
res = Residual([down, up])
res(x)

tensor([5])

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Residual_blocks_no_last2.png?raw=true)

#### Addition

`torchlego` comes with an useful `ResidualAdd` block that is just a `Residual` that performs automatically addition

In [13]:
import torch
from torchlego.blocks import ResidualAdd, Lambda

layer = ResidualAdd([Lambda(lambda x: x)])
layer(torch.tensor([1]))

tensor([2])

A more complete example

In [14]:
import torch.nn as nn
from torchlego.blocks import ResidualAdd

x = torch.rand((1, 64, 8, 8))

block = nn.Sequential(conv3x3_bn_act(64, 64, padding=1))

layer = ResidualAdd([block])
x = layer(x)

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Add_block.png?raw=true)

You can pass multiple blocks

In [15]:
from torchlego.blocks import ResidualAdd, Lambda

blocks = [Lambda(lambda x: x), Lambda(lambda x: x)]
layer = ResidualAdd(blocks)
layer(torch.tensor(1))

tensor(4)

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Add_blocks.png?raw=true)

Let's create a basic [ResNet](https://arxiv.org/abs/1512.03385) block


In [16]:
from torchlego.blocks import conv_bn

def resnet_basic_block(in_features, out_features):
    shortbut = conv_bn(in_features, out_features, kernel_size=1, stride=2, bias=False) if in_features != out_features else nn.Identity()
    stride = 2 if in_features != out_features else 1
    return nn.Sequential(
                ResidualAdd(nn.ModuleList([
                    nn.Sequential(
                        conv3x3_bn_act(in_features, out_features, stride=stride, padding=1, bias=False),
                        conv3x3_bn(out_features, out_features, padding=1, bias=False))]), 
                    shortcut=shortbut),
                nn.ReLU())
    
resnet_basic_block(32, 64)

Sequential(
  (0): Residual(
    (blocks): ModuleList(
      (0): Sequential(
        (0): Sequential(
          (0): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU()
        )
        (1): Sequential(
          (0): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
    )
    (shortcut): Sequential(
      (0): Conv2d(32, 64, kernel_size=(1, 1), stride=(2, 2), bias=False)
      (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (1): ReLU()
)

![alt](https://github.com/FrancescoSaverioZuppichini/torchlego/blob/develop/doc/images/Add_resnet.png?raw=true)

What about a full `resnet`? Easy peasy

In [17]:
def resnet(in_features, n_classes, sizes):
    return nn.Sequential(
        nn.Conv2d(in_features, 64, kernel_size=7, stride=2, padding=3),
        nn.BatchNorm2d(64),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=3, stride=2, padding=1),
        nn.Sequential(*[resnet_basic_block(64, 64) for _ in range(sizes[0])]),
        resnet_basic_block(64, 128),
        nn.Sequential(*[resnet_basic_block(128, 128) for _ in range(sizes[1] - 1)]),
        resnet_basic_block(128, 256),
        nn.Sequential(*[resnet_basic_block(256, 256) for _ in range(sizes[2] - 1)]),
        resnet_basic_block(256, 512),
        nn.Sequential(*[resnet_basic_block(512, 512) for _ in range(sizes[3] - 1)]),
        nn.AdaptiveAvgPool2d(1),
        nn.Flatten(),
        nn.Linear(512, n_classes)
)
x = torch.rand((1,3,224,244))

resnet34 = resnet(3, 1000, [3, 4, 6, 3])

resnet34(x).shape

torch.Size([1, 1000])

![alt](https://www.researchgate.net/profile/Aaron_Vose/publication/330400293/figure/fig6/AS:715395283558403@1547574935970/ResNet-neural-network-architecture-ResNet-34-pictured-image-from-11.ppm)

### Unet

What about Unet?

In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchlego.blocks import ResidualCat2d, Lambda
from torchlego.blocks import Residual, conv3x3, conv3x3_bn_act, conv1x1

down = lambda in_features, out_features: nn.Sequential(
    nn.MaxPool2d(kernel_size=2, stride=2),
    conv3x3_bn_act(in_features, out_features, padding=1),
    conv3x3_bn_act(out_features, out_features, padding=1),
)

class up(nn.Module):
    def __init__(self, in_features, out_features, should_up=True, *args, **kwargs):
        super().__init__()
        self.up = nn.ConvTranspose2d(in_features, out_features, kernel_size=2, stride=2)
        self.should_up = should_up
        self.blocks =nn.Sequential(
            conv3x3(out_features * 2, out_features, padding=1),
            conv3x3(out_features, out_features, padding=1),
    )

    def forward(self, x, res):
        if self.should_up: x = self.up(x)
            
        diffX = x.size()[2] - res.size()[2]
        diffY = x.size()[3] - res.size()[3]
        pad = (diffX // 2, diffX // 2, diffY // 2, diffY // 2)
        res = F.pad(res, pad)
        
        x = torch.cat([res, x], dim=1)
        out = self.blocks(x)
        return out

unet = nn.Sequential(
    Residual([
    nn.ModuleList([
        nn.Sequential(
            conv3x3_bn_act(3, 64),
            conv3x3_bn_act(64, 64)),
        down(64, 128),
        down(128, 256),
        down(256, 512),
        down(512, 1024),
    ]),
    nn.ModuleList([
        up(512 * 2, 512),
        up(256 * 2, 256),
        up(128 * 2, 128),
        up(64 * 2, 64),

    ])
]),         
    conv1x1(64, 2)
)

x = torch.rand((1,3,256,256))

unet(x)

tensor([[[[ 0.1703,  0.1333,  0.1065,  ...,  0.0960,  0.0289,  0.2440],
          [ 0.0541,  0.1370, -0.0009,  ..., -0.0234,  0.1766,  0.1227],
          [ 0.0071,  0.0103, -0.0728,  ..., -0.0840,  0.0448,  0.0931],
          ...,
          [ 0.0387,  0.0116,  0.1317,  ...,  0.0861,  0.0679,  0.1378],
          [ 0.0253,  0.0583, -0.0304,  ..., -0.0590, -0.0112,  0.0985],
          [ 0.1501,  0.1165,  0.0767,  ...,  0.0516,  0.0438,  0.0853]],

         [[ 0.0734,  0.1631, -0.0388,  ..., -0.0313, -0.0182, -0.0158],
          [ 0.0150, -0.0157, -0.1313,  ...,  0.0417, -0.0827,  0.0312],
          [-0.0783, -0.1002, -0.0104,  ..., -0.0625,  0.1027, -0.0133],
          ...,
          [-0.0326, -0.0716, -0.0284,  ..., -0.0891, -0.0317, -0.0103],
          [ 0.1046, -0.0530, -0.0447,  ...,  0.0813, -0.0651,  0.0246],
          [-0.0351,  0.0342, -0.0398,  ..., -0.0206, -0.0515,  0.0425]]]],
       grad_fn=<ThnnConv2DBackward>)

### TODO

- [ ] if second number is not passed in conv just use the first one
- [ ] in all the sequential use OrderDict to name them
- [ ] little doc for module transfer

